# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170927_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='friendliness',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='breed',
            name='trainability',
            field=models.IntegerField(default=1),
        ),
    ]
