# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170928_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dog',
            name='favoritefood',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='dog',
            name='favoritetoy',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=1000),
        ),
    ]
