# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170928_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='friendliness',
            field=models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='trainability',
            field=models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')]),
        ),
    ]
